name: TinkerVerse CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('server/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build server (debug)
        shell: bash
        run: |
          cd server
          cargo build --locked

      - name: Upload dev artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tv-dev-artifacts
          path: |
            server/target/debug/astral-server.exe
            client2dweb/**
